<?php

/**
 * Model_AclRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AclRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AclRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_AclRole');
    }
}