<?php

/**
 * Model_AclTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AclTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AclTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Acl');
    }
    public static function addResourceIfNonExistant($strModuleName, $strControllerName, $strActionName){
        $q = Doctrine_Query::create()
        ->select('a.id')
        ->from('Model_Acl a')
        ->where('a.module = ?', $strModuleName)
        ->andWhere('a.controller = ?', $strControllerName)
        ->andWhere('a.action = ?', $strActionName);

        $q->getSqlQuery();
        $result=$q->execute()->toArray();
        
        if(empty($result)){        
            $aclroleTable = new Model_Acl();  
            $aclroleTable->module=$strModuleName;
            $aclroleTable->controller=$strControllerName;
            $aclroleTable->action=$strActionName;
            $aclroleTable->save();
        }
    }
    
}