<?php

/**
 * Model_ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Contact');
    }
}