<?php

/**
 * Model_DenyAclTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_DenyAclTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_DenyAclTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_DenyAcl');
    }
}