<?php

/**
 * Model_RolesInheritancesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RolesInheritancesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RolesInheritancesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RolesInheritances');
    }
}