<?php

/**
 * Model_Base_Acl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module
 * @property string $controller
 * @property string $action
 * @property Doctrine_Collection $AclRole
 * @property Model_AllowAcl $AllowResources
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Acl extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('acl');
        $this->hasColumn('module', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('controller', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('action', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_AclRole as AclRole', array(
             'local' => 'id',
             'foreign' => 'acl_id'));

        $this->hasOne('Model_AllowAcl as AllowResources', array(
             'local' => 'id',
             'foreign' => 'acl_id'));
    }
}