<?php

/**
 * Model_Base_RolesInheritances
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_role_id
 * @property integer $role_id
 * @property integer $position
 * @property Model_Role $Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_RolesInheritances extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('roles_inheritances');
        $this->hasColumn('parent_role_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}