<?php

/**
 * Model_Base_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $role
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $AclRole
 * @property Model_RolesInheritances $RolesInheritances
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Role extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('role');
        $this->hasColumn('role', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_User as User', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Model_AclRole as AclRole', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasOne('Model_RolesInheritances as RolesInheritances', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}