<?php

/**
 * Model_Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $password
 * @property integer $contact_id
 * @property string $address
 * @property integer $role_id
 * @property Model_Contact $Contact
 * @property Model_Role $Role
 * @property Doctrine_Collection $User
 * @property Model_AllowAcl $AllowResources
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('contact_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Contact as Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Role as User', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasOne('Model_AllowAcl as AllowResources', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}